export const termsData:ITermsData = {
    heading:"Terms of Service",
    date:"25 Dec,2023",
    intro:"Thanks for using our products and services ('Services'). The Services are provided by CGBiz Corporation ('Scribie'), located at 44 Tehama St., San Francisco, CA 94105, United States. By using our Services, you are agreeing to these terms including any subsequent changes or modifications. Please read them carefully. If you do not agree to these Terms or our Privacy Policy, please do not use the Scribie.com website or any of our Services and products. Our Services are very diverse, so sometimes additional terms or product requirements (including age requirements) may apply. Additional terms will be available with the relevant Services, and those additional terms become part of your agreement with us if you use those Services.",
    detailedData:[
        {title:"Personal Data",description:'Personal Data is any information that relates to an identified or identifiable individual. The Personal Data that you provide directly to us through our Sites will be apparent from the context in which you provide the data. In particular:When you register for a Scribie account we collect your full name, email address, IP Addresses, browser fingerpring and account log-in credentials. When you fill-in our online form to contact our sales team, we collect your full name, work email, country, and anything else you tell us about your project, needs and timeline.When you use the "Remember Me" feature of Scribie account, we collect your email address, password, IP Address and cookie preferences.When you respond to Scribie emails or surveys we collect your email address, name and any other information you choose to include in the body of your email or responses. If you contact us by phone, we will collect the phone number you use to call Scribie. If you contact us by phone as a Scribie User, we may collect additional information in order to verify your identity.'},
        {title:"Collected Information",description:"We also may collect information about your online activities on websites and connected devices over time and across third-party websites, devices, apps and other online features and services. We use Google Analytics on our Sites to help us analyze Your use of our Sites and diagnose technical issues.To learn more about the cookies that may be served through our Sites and how You can control our use of cookies and third-party analytics, please see our Cookie Policy."},
        {title:"Privacy & Copyright Protection",description:'Scribie\'s privacy policies explain how we treat your personal data and protect your privacy when you use our Services. By using our Services, you agree that Scribie can use such data in accordance with our privacy policies.We respond to notices of alleged copyright infringement and terminate accounts of repeat infringers according to the process set out in the U.S. Digital Millennium Copyright Act.We provide information to help copyright holders manage their intellectual property online. If you think somebody is violating your copyrights and want to notify us, you can find information about submitting notices and Scribie\'s policy about responding to notices in our Help Center.'},
        {title:"Derivative Products",description:"Some of our Services allow you to upload, submit, store, send or receive content. You retain ownership of any intellectual property rights that you hold in that content. In short, what belongs to you stays yours.When you upload, submit, store, send or receive content to or through our Services, you give Scribie (and those we work with) a worldwide license to use and create derivative works (such as those resulting from machine learning models or other statistical models we make so that your content works better with our Services). The rights you grant in this license are for the limited purpose of operating, promoting, and improving our Services, and to develop new ones. This license continues even if you stop using our Services. Some Services may offer you ways to access and remove content that has been provided to that Service. Also, in some of our Services, there are terms or settings that narrow the scope of our use of the content submitted in those Services. Make sure you have the necessary rights to grant us this license for any content that you submit to our Services.CGBiz Corporation does not sell, rent or share personal information or data with any third parties under any circumstances."},
        {title:"Privacy & Communications",description:"You acknowledge and agree that that CGBiz Corporation may occasionally send you communications regarding your account or the Service via email.You can control the email notifications from your account settings page. There may also be direct communications from our support executives whenever we have to follow up or have questions regarding your files. See the Privacy Policy, which is incorporated into this Agreement by reference."},
        {title:"Accounts, Passwords & Security",description:"You must be a registered user to access the Service. You are responsible for keeping your password secure. You will be solely responsible and liable for any activity that occurs under your registered account.Please contact support in case you detect a breach of your account or any unauthorized use. You may also delete your account from the settings page anytime you wish. You may have to clear any dues and cancel any in-progress orders or Service."},
        {title:"Transcription Rates",description:"CGBiz Corporation reserves the sole right to alter, modify, change or withdraw the transcription rates offered or quoted for a specific file or all files or as stated on our website. We may ask for additional payment depending on our assessment of the time and effort required, such assessment to be in good faith. By using our Services you acknowledge and agree that our assessment is final and binding and refusal to accept that will lead to immediate cancellation of the order. For the avoidance of doubt, no fees are payable by you for any such cancelled orders where additional charges were levied."},
        {title:"Acceptable Use & Conduct",description:"You are solely responsible for the data which is submitted to CGBiz Corporation in relation to the Service. You agree to indemnify, defend, hold harmless CGBiz Corporation and its suppliers from any and all loss, cost, liability and expense arising from or related to your data, your use of the Service or your violation of these terms. You agree to defend and/or settle any third party claim, action, suit or proceeding made against CGBiz Corporation and its suppliers alleging that CGBiz Corporation’s use of your data or files infringes the intellectual property rights of a third party ('IP Claim'), provided CGBiz Corporation will give you (a) prompt written notice of such IP Claim, (b) sole control over the defense and settlement of such claim, and (c) cooperation in the defense of the claim. Your obligation for such IP Claim will not apply if the actual or alleged infringement results solely from any unauthorized modification, alteration or addition to your data or files.The Software and Services are made available to you, your company, and/or your customers for personal or commercial use, which use must be in compliance with all applicable laws, rules and regulations and must not infringe or violate third party rights.Any unauthorized use of any CGBiz Corporation's Service is a violation of this Agreement and certain federal and state laws. Such violations may subject the unauthorized user and his or her agents to civil and criminal penalties."},
        {title:"Chargeback & Refund Policy",description:"CGBiz Corporation will not, under any circumstances, issue cash refunds for any orders. If you have a question about an order, please contact us immediately. If the charges were made in error, we will credit your account or credit card account for the amount that was charged in error. CGBiz Corporation reserves the right to suspend and/or terminate a customer’s account any customer who disputes a credit card payment that is found to be valid will. Any past due fees and costs will be sent to collections. If our collection efforts fail, unpaid debts will be reported to all available credit reporting agencies"},
        {title:"Warranties & Representations",description:"CGBiz Corporation represents and warrants that it will provide personnel with sufficient skill and knowledge to perform the Service and that the Service will be performed in a professional and workmanlike manner. Except for the foregoing warranty, you understand and agree that the Software and Service is provided as is and CGBiz Corporation its affiliates, suppliers and Resellers expressly disclaim all warranties of any kind, beyond the refund or re-review, whichever is applicable, express or implied, including without limitation any warranty of merchantability, fitness for a particular purpose, non-infringement or bailment of your data on CGBiz Corporation's servers.CGBiz Corporation, its affiliates, suppliers and Resellers make no warranty or representation, other than the refund or re-review, whichever is applicable, regarding the results that may be obtained from the use of the Service, the security of the Service, or that the Service will meet any user's requirements beyond the re-review. Use of the Service is at your sole risk. You will be solely responsible for any damage to You resulting from the use of the Service. The entire risk arising out of use, security or performance of the Service remains with you.Without limiting the foregoing, the Service is not designed or licensed for use in hazardous environments requiring fail-safe controls, including without limitation operation of nuclear facilities, aircraft navigation/communication systems, air traffic control, and life support or weapons systems."},
        {title:"Limitation of Liability",description:"In no event shall CGBiz Corporation be liable for any indirect, special, incidental, consequential or punitive damages (including but not limited to loss of use, loss of profits, or loss of data) whether in an action in contract, tort (including but not limited to negligence), equity or otherwise, arising out of or in any way connected with the use of or inability to use this site or the materials therein or resulting from unauthorized access to or alteration of data."},
        {title:"Termination of Service",description:"We reserve the right to terminate or suspend your account at any time. You also have the option of canceling your account at any time without penalty. In the event of account cancelation you will lose all data related to your account. We also reserve the right to refuse service without providing a reason."},
        {title:"Conditions",description:"We reserve the right to modify these Terms of Service at any time without notice. Please review these Terms of Service on occasion as they may change in the future. We may, but have no obligation to, remove accounts and content containing what we determine, in good faith and on reasonable grounds, as unlawful, offensive, threatening, defamatory, obscene or otherwise objectionable material. We will remove content that violates any party's intellectual property, if we have been notified of such violation, or these Terms of Service. An account terminated by CGBiz Corporation will not be backed-up for any reason and will be immediately deleted from our servers."},
        {title:"Intellectual Property",description:"CGBiz Corporation claims no intellectual property rights over the material or content that you provide to the Service. You acknowledge that CGBiz Corporation owns all right, title and interest in and to the Service, including without limitation all intellectual property rights, and such rights are protected by US and international intellectual property laws. You agree that you will not copy, reproduce, alter, modify or create derivative works from the Service."}
    ]
}

export const privacyData:ITermsData = {
    heading:"Privacy Policy",
    date:"25 Dec,2023",
    intro:"We collect personal information in a number of ways when you visit our site or use our service. For example, you provide us with personal information when you register for an account or contact us by email. CGBiz Corporation automatically receives and records information from your browser, including your IP address and cookies. The personal information collected is used for billing, identification, authentication, service improvement, research, and contact.We are committed to conducting our business in accordance with these principles in order to ensure that the confidentiality of personal information is protected and maintained.If you have questions or concerns about CGBiz Corporation's Privacy Policy please send us a message here.",
    detailedData:[
        {title:"Cookies",description:'A cookie is a small amount of data that is sent to your browser from our servers and stored on your computer\'s hard drive. We use cookies to access information when you sign in, store your preferences, and to keep you logged in. You can configure your browser to accept or reject these cookies.'},
        {title:"Information Sharing",description:"CGBiz Corporation does not sell, rent or share personal information with any third parties under any circumstances. We may, however, disclose personal information when we believe it violates our Terms of Service or is appropriate to comply with the law, to protect our or our users' rights, as well as to protect our users from fraudulent, abusive, and unlawful use of our site. We reserve the right to disclose your personally identifiable information as required by law and when we believe that disclosure is necessary to protect our rights and/or to comply with a judicial proceeding, court order, or legal process served on our website."},
        {title:"Client Data & Storage",description:'CGBiz Corporation ensures that all the files, transcripts and data remain private and confidential. Access is restricted strictly on a need to know basis to our employees and contractors. All employees and contractors are required to sign a Non Disclousure Agreement before being allowed access to the data. Due to the sensitive nature of the recordings and transcripts we take privacy very seriously and make it our primary concern for all our customers.'},
        {title:"Information Security",description:"We restrict access of information to CGBiz Corporation employees, contractors and agents who need to know that information in order to operate, develop or improve our transcription service. These individuals are bound by confidentiality obligations and may be subject to discipline, including termination and criminal prosecution, if they fail to meet these obligations."},
        {title:"Changes",description:"CGBiz Corporation will notify customers by email about any significant changes in this policy.Please contact support in case you detect a breach of your account or any unauthorized use. You may also delete your account from the settings page anytime you wish. You may have to clear any dues and cancel any in-progress orders or Service."}
    ]
}

export interface ITermsData {
    heading: string;
    date: string;
    intro: string;
    detailedData: {
        title: string;
        description: string;
    }[];
}